vars:
  - src/params.py

stages:
  prepare-dataset:
    cmd: python -m src.data_tools.prepare_data
    deps:
      - ${Dataset.path}
      - src/data_tools/prepare_data.py
    params:
      - src/params.py:
          - PreparedDataset.save_path
          - PreparedDataset.vocab_path
    outs:
      - ${PreparedDataset.save_path}
      - ${PreparedDataset.vocab_path}
  train-and-evaluate:
    cmd: python -m src.train.train
    deps:
      - ${PreparedDataset.save_path}
      - ${PreparedDataset.vocab_path}
      - src/train/train.py
    params:
      - src/params.py:
          - Split
          - Model
          - Optimizer
          - Training
          - Evaluation